### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by k20stitch** [Cairath/tools-not-included#12]
**Describe the bug**
Using the manual version, everything is up to date, I hit okay, I get the list of geysers and stuff... but my seed is never actually uploaded to the site.

**Comment by Cairath** [comment]
Hey,

there are two options -- either the seed was a rare case where something glitched and there are no at least 2 cool steam geysers and 1 nat gas geyser (or is odd enough that it doesn't satisfy normal world generation rules -- happens very, very rarely on specific seeds), or a seed with this number already exists.

If you have the seed number that was failing, feel free to drop it here and I'll check what is happening

**Comment by k20stitch** [comment]
It was an odd seed because one of the cool steam geysers was overwritten by an POI. It had 3 NAT gas geysers. Even weirder is your site actually does support seeds with one cool steam vent... ironically they all seem to be from qol2

**Comment by Cairath** [comment]
I just checked -- I have in fact loosened the restriction to 1 cool steam geyser and simply forgot. :P

There's one more thing I just thought of - the game handles magma biome zone type in a weird way - it's the same type as the caustic biome which was messing up the visual map generation. The mod overrides the zone type for that biome in game files, and the server will reject the seed if incorrect number of biomes is delivered - which can happen if your game for some reason has no write permissions in its folder, which is not that rare with windows.

`...\steamapps\common\OxygenNotIncluded\OxygenNotIncluded_Data\StreamingAssets\worldgen\subworlds\Bottom.yaml` - the zoneType should be MagmaCore, not ToxicJungle. If this is not the case either, I'm out of ideas without an actual seed number.

I really need to add this to FAQ... D:

**Comment by realthecaffiend** [comment]
Hey there, I found this issue while searching for something related to my problem, and I think this may be the same; I am running Q3-336724 of the game client, I just downloaded modloader and the manual update mod; I regenerated a new world with the same seed as my existing one (Because I'm 150 cycles in already), paused, and hit upload seed. It thanked me, told me some geyser information, etc, but the seed I uploaded (2079339403) does not seem to show up on the site. I also checked the YAML file you listed, and the zoneType is in fact MagmaCore. Also, pursuant to the other discussion, I know there are two natgas and two cool steam, because I've run into them already, so I believe it's not getting cut as a weird/useless seed? 

Now I'm a new user and I assumed I could just search the seed as soon as I uploaded; do I need to assign any other criteria besides seed for the search? Is it instant-ish, or like a nightly batch job? Let me know if I'm just missing something :)

**Comment by Cairath** [comment]
It should be searchable as soon as it is uploaded. 
I'm going to block uploads until release - since modloader is no longer needed and I'm updating everything to the launch upgrade all seeds will be deleted soon anyway.  

Sorry for the inconvenience - when the game goes out of early access soon things will be freshly tested and working :)

**Comment by realthecaffiend** [comment]
Aw, I wanted to find my volcanos the lazy way! .... And hope I have any at all. Thanks for all your work on this, the random generation of worlds in ONI is super interesting but the occasional nearly-unplayable one is... tricky; This helps to constrain that RNG somewhat

**Comment by Cairath** [comment]
I'll be home in 20 minutes so I'll check what went wrong with that one

**Comment by Cairath** [comment]
The log claims there was incorrect number of biomes, which usually happened if magma was marked incorrectly. :/

**Comment by realthecaffiend** [comment]
Huh, interesting. I guess I'll have to manually explore for now until the actual release version; If it's any help for future troubleshooting, I dropped the contents of subworlds/Bottom/yaml below though

`name: Bottom
zone:
  biomeNoise: noise/StartWorld
  temperatureRange: VeryHot
  minChildCount: 4
  density:
    min: 35
    max: 45
  avoidRadius: 50.0
  sampleBehaviour: PoissonDisk
  biomes:
    - name: biomes/Misc/MagmaBed
      weight: 1
      #overrides:
      #  massMultiplier: 50
  tags:
  - IgnoreCaveOverride
  zoneType: MagmaCore`

**Comment by k20stitch** [comment]
I ran into issues like this if the world contains less than 2 cool steam vents (like if one is overwritten by a poi)

**Comment by Cairath** [comment]
Those were intentionally rejected. This version will be deprecated within two weeks so I won't touch these issues, in the new version i handle uploads differently which should reduce the number of rejections
