### ISSUE TITLE
Map Browser Search Optimization

### ISSUE THREAD

**Issue by jvanalst** [Cairath/tools-not-included#56]
---
name: Feature request
about: Map Browser Search Optimization
---

**Is your feature request related to a problem? Please describe.**
I noticed that the more fields you search on the worse and worse the performance of the Map Browser search function. Once you have 9 or ten fields it tends to give out entirely (currently I suspect a server or database query timeout). This seems especially true when filtering at the cluster level.

**Describe the solution you'd like**
I'd love to take a crack at optimizing the Search to make it more performant.

**Describe alternatives you've considered**
You could optimize the search?

**Additional context**
I'm a Full Stack Web Developer with more than a decade of experience. I'm intimately familiar with MySQL/MariaDB, JavaScript, HTML, CSS, and I'm also fluent in PHP.

**Comment by Cairath** [comment]
SO/cluster support was hastily added over the course of 2 weeks during christmas, optimizations have been on the docket since then, however life has had other things planned. It's a mix of optimization and lack of resources, the site has surprisingly a lot of traffic, but I can't throw more money at the problem.

Since worldgen changes are coming with the new update that is on the public testing branch right now, I'll probably take a look at it then.

The relevant techs here would be .NET Core, Entity Framework Core and MS SQL, however I am not planning on sharing the source, so unfortunately it'll have to wait til I have the time to tinker with it.

**Comment by kingrodriguez** [comment]
@Cairath even tho you are not sharing the src, i would participating in the project.

i am considering providing an api, if you are willing to share the data and let me know about how much traffic we talking

just to give you an overview: i would use python, fastapi and openapi standard to auto-generate api clients for the frontend.

**Comment by Cairath** [comment]
Thanks but no is a no. It's not "just an api", it's entire backend and integration with mods, and why on earth would I want it rewritten in techs I don't work with.

**Comment by kingrodriguez** [comment]
because you would not need to mess with it anymore, in case you dont want.

i would provide you with 3 endpoints:
- img upload
- data upload
- data query

in case your mod reports new data, the mod itself or your backend can make the post requests to add data and in your frontend you can query the data.
the api is [openapi](https://www.openapis.org/) compatible and client generation is easily automated.

unfortunately i lack knowledge of modding, so data aquisition would be hard for me. but i du APIs and SPAs for a living.

if you provide me test data sample or allow me to scrape your existing data, i would create an api, host it and you can decide if you want to use it or not.

so the workload is on my side and you got nothing to lose.
